# Generated by Django 3.1.4 on 2020-12-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_models", "0009_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="OutOfAJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("class_var", models.CharField(max_length=50)),
                ("class_var2", models.CharField(max_length=50)),
            ],
        ),
    ]
